import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { TopWarning } from "@/components/layout/top-warning";
import { DeliveryWindow } from "@/components/layout/delivery-window";
import { Providers } from "@/providers/provider";
import Footer from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${spaceGrotesk.className} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col overflow-x-hidden" suppressHydrationWarning>
        <Providers>
          <TopWarning />
          <DeliveryWindow />
          <Navbar />
          <div className="flex-1">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
